In [1]:
import torch

In [2]:
def sigmoid(x):
    return 1/(1+torch.exp(-x))
#defining the activation function

In [4]:
#generating random data for the model
torch.manual_seed(7)
#as so things are in range and predictable
#and we can regenerate the result

features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

#for generating random numbers 

print(features)
print(bias)
print(weights)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[0.3177]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


In [5]:
#forming a network by these weights and biases
y_a = sigmoid(torch.sum(features*weights)+bias)
#2 methods of sum
y_b = sigmoid((features*weights).sum()+bias)

print(y_a)
print(y_b)

tensor([[0.1595]])
tensor([[0.1595]])


In [7]:
#we can do the same thing with matmul operation
#first we need to take the transform of the matrix and then perform the matmul operation
#there are many ways to reshape the tensor in pytorch
#1.reshape
#2.resize_(inplace operation)do not make a copy directly change in memory
#3.view
#best is view
y = sigmoid(torch.mm(features,weights.view(5,1))+bias)
print(y)

tensor([[0.1595]])


In [14]:
#we can do for multilayer preceptrons too
##doing multilayer
torch.manual_seed(7)
features = torch.randn((1,3))
#no of inputs must have as same as features number
#defining the size of layers
n_input = features.shape[1]
n_hidden = 2
n_output = 1

#defining the weights
W1 = torch.randn(n_input,n_hidden)
W2 = torch.randn(n_hidden,n_output)

#defining the bias term
B1 = torch.randn(1,n_hidden)
B2 = torch.randn(1,n_output)

print(W1)
print(W2)
print(B1)
print(B2)

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])
tensor([[0.2405]])


In [16]:
#making the network
h = sigmoid(torch.mm(features,W1)+B1)
output = sigmoid(torch.mm(h,W2)+B2)
print(output)

tensor([[0.3171]])


In [17]:
#NUMPY and torch are closely related
#we can easily interconvert them and viceversa
import numpy as np

In [19]:
a = np.random.rand(4,3)
a

array([[0.31606812, 0.86078419, 0.4595105 ],
       [0.02072873, 0.93734627, 0.94025429],
       [0.915174  , 0.03690767, 0.37494326],
       [0.88085644, 0.96505805, 0.50814503]])

In [20]:
b = torch.from_numpy(a)
b

tensor([[0.3161, 0.8608, 0.4595],
        [0.0207, 0.9373, 0.9403],
        [0.9152, 0.0369, 0.3749],
        [0.8809, 0.9651, 0.5081]], dtype=torch.float64)

In [21]:
b.numpy()

array([[0.31606812, 0.86078419, 0.4595105 ],
       [0.02072873, 0.93734627, 0.94025429],
       [0.915174  , 0.03690767, 0.37494326],
       [0.88085644, 0.96505805, 0.50814503]])

In [22]:
#All the things we have done here are inplace and anything we change in numpy change in torch too
b.mul_(2)

tensor([[0.6321, 1.7216, 0.9190],
        [0.0415, 1.8747, 1.8805],
        [1.8303, 0.0738, 0.7499],
        [1.7617, 1.9301, 1.0163]], dtype=torch.float64)

In [23]:
a

array([[0.63213624, 1.72156838, 0.91902099],
       [0.04145746, 1.87469254, 1.88050857],
       [1.830348  , 0.07381534, 0.74988652],
       [1.76171289, 1.93011611, 1.01629006]])